import { Button } from '@/components/ui/button'
import React from 'react'
import Link from 'next/link'
import Image from 'next/image'

import InterviewCard from '@/components/InterviewCard'
import LoadMoreInterviews from '@/components/LoadMoreInterviews'
import { getCurrentUser } from '@/lib/action/auth.action'
import { getInterviewsByUserId, getLatestInterviews } from '@/lib/action/general.action'
 async function Home(props: { searchParams: Promise<{ [key: string]: string | string[] | undefined }> }) {
  const searchParams = await props.searchParams;
  const query = typeof searchParams.query === 'string' ? searchParams.query.toLowerCase() : '';

  const user = await getCurrentUser();
  const [userInterviews, latestInterviews] = await Promise.all([
    await getInterviewsByUserId(user?.id!),
    await getLatestInterviews({userId : user?.id!, limit: 100}) // Fetched more to allow useful client search
  ])

  let filteredLatestInterviews = latestInterviews || [];
  if (query) {
    filteredLatestInterviews = filteredLatestInterviews.filter((interview) => {
      const matchRole = interview.role?.toLowerCase().includes(query);
      const matchTech = interview.techstack?.some(t => t.toLowerCase().includes(query));
      return matchRole || matchTech;
    });
  }
 
  const hasPastInterviews = (userInterviews?.length??0)>0;
  const hasUpcomingInterviews = filteredLatestInterviews.length > 0;
 
  return (
    <>
      <section className="card-cta">
        <div className="flex flex-col gap-5 max-w-xl">
          <h2 className="text-2xl font-bold text-light-100 tracking-tight max-sm:text-xl">
            Elevate your interview preparation with AI assistance.
          </h2>
          <p className="text-light-400 text-base leading-relaxed">
            Experience real interview scenarios and get feedback instantly.
          </p>
          <Button asChild className="btn-primary max-sm:w-full w-fit">
            <Link href="/interview">Start your Interview</Link>
          </Button>
        </div>
        <Image
          src="/robolap.jpg"
          alt="AI assistant"
          width={360}
          height={360}
          className="max-sm:hidden object-fill"
        />
      </section>

      <section className="flex flex-col gap-5">
        <h2 className="text-xl font-semibold text-light-100">Your Interviews</h2>
        <div className="interviews-section">
          {hasPastInterviews ? (
            userInterviews?.map((interview) => (
              <InterviewCard {...interview} key={interview.id} />
            ))
          ) : (
            <p className="text-light-600 rounded-xl border border-white/10 bg-dark-200/50 px-6 py-8 text-center">
              You haven&apos;t taken any interviews yet.
            </p>
          )}
        </div>
      </section>

      <section className="flex flex-col gap-5 mt-4">
        <h2 className="text-xl font-semibold text-light-100">
          {query ? `Search Results for "${query}"` : "Interview Generated By Other Users"}
        </h2>
        <LoadMoreInterviews interviews={filteredLatestInterviews || []} />
      </section>
    </>
  )
}

export default Home